version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn gcs_file_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    entrypoint: ["/app/entrypoint.sh", "web"]
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials.json"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A gcs_file_manager worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    entrypoint: ["/app/entrypoint.sh", "celery"]

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_broker
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
